### ISSUE TITLE
model双向绑定问题

### ISSUE THREAD

**Issue by zjz19901029** [xuqiang521/overwrite#3]
<input x-model="name" type="text">
<span>{{name}}</span>
输入框更改内容后，span中内容会同时改变，这个时候，使用vm.name="xxxxxx",只有span的内容变化，input中的内容不会改变。

在model的compileUtil中设置完vm值后，应该将$elm设为undefined，这样updater中，不会因为判断$elm === node直接return。

timer = setTimeout(function() {
                    self._setVmVal(vm, exp, newVal);
                    val = newVal;
                    **$elm = undefined;**
                })

**Comment by xuqiang521** [comment]
overwrite里面的这个版本里面的一些东西只是实现一些比较simple的数据驱动，功能稍微全一点你可以参考我的Xue项目，里面需求也在不定期做迭代。[Xue](https://github.com/xuqiang521/Xue  )
