### ISSUE TITLE
Links was failed

### ISSUE THREAD

**Issue by kunkuntang** [xuqiang521/overwrite#4]
The links below Readme.md file was redirect to 404

**Comment by xuqiang521** [comment]
e~.  Can you please tell me which link and then I can have a good look at where the problem. thanks !

**Comment by kunkuntang** [comment]
remove the duplicate element in array, deep copy, observe pattern, Promise, MVVM these links in the Processing part of README.md were unavailable 😊

**Comment by xuqiang521** [comment]
#9b2f6c477b9ef61b4b171f739abd13c7913c4d76

**Comment by xuqiang521** [comment]
#4 https://github.com/xuqiang521/overwrite/commit/9b2f6c477b9ef61b4b171f739abd13c7913c4d76
